In [1]:
#1. Import the NUMPY package under the name np.

#[your code here]

import numpy as np


In [3]:
#2. Print the NUMPY version and the configuration.

#[your code here]

print(f"NumPy version: {np.__version__}")
np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/isabel.lopes/AppData/Local/anaconda3/Library/include
    lib directory: C:/Users/isabel.lopes/AppData/Local/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian:

In [5]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

#[your code here]

#Method 1

a = np.random.randint(0, 100, (2, 3, 5))

#Method 2

a = np.random.rand(2, 3, 5)


#Method 3

a = np.random.random((2, 3, 5))



[[[71 24 60 94  3]
  [48 61 73 79 97]
  [ 1 18 89 86 53]]

 [[81 25 23 90 47]
  [89 98 18 48 52]
  [66 26 45 90 34]]]
[[[0.93604842 0.33892182 0.29631836 0.18957936 0.29747244]
  [0.71472309 0.62741624 0.22078688 0.79423861 0.99271221]
  [0.62844636 0.9486524  0.04448636 0.54792196 0.7204797 ]]

 [[0.65212685 0.33952296 0.55893382 0.05934581 0.14386598]
  [0.99270678 0.03846575 0.76343982 0.24925031 0.24514334]
  [0.12836975 0.89820601 0.51694895 0.86143238 0.38985289]]]
[[[0.30429719 0.96764391 0.52616975 0.43786554 0.72113294]
  [0.71453878 0.66059798 0.09831853 0.05460183 0.5770227 ]
  [0.42638266 0.85724564 0.56413599 0.02797983 0.59646838]]

 [[0.5264602  0.21354076 0.13775215 0.18327499 0.8890365 ]
  [0.8344566  0.07674443 0.05630981 0.0211732  0.00271911]
  [0.40654824 0.385428   0.20343194 0.86626533 0.10521698]]]


In [6]:
#4. Print a.

#[your code here]

print(a)

[[[0.30429719 0.96764391 0.52616975 0.43786554 0.72113294]
  [0.71453878 0.66059798 0.09831853 0.05460183 0.5770227 ]
  [0.42638266 0.85724564 0.56413599 0.02797983 0.59646838]]

 [[0.5264602  0.21354076 0.13775215 0.18327499 0.8890365 ]
  [0.8344566  0.07674443 0.05630981 0.0211732  0.00271911]
  [0.40654824 0.385428   0.20343194 0.86626533 0.10521698]]]


In [8]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the arry to variable "b"

#[your code here]

b = np.ones((5, 2, 3))

In [9]:
#6. Print b.

#[your code here]

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
#7. Do a and b have the same size? How do you prove that in Python code?

#[your code here]

print("Size of a:", a.size)
print("Size of b:", b.size)

if a.size == b.size:
    print("array a and b have the same size")
else:
    print("array a and b do not have the same size")


Size of a: 30
Size of b: 30
array a and b have the same size


In [22]:
#8. Are you able to add a and b? Why or why not?

#[your code here]

print("Shape of a",a.shape)
print("Shape of b",b.shape)

result = a+b

#It is not possible to add a and b because their last dimenson is different

Shape of a (2, 3, 5)
Shape of b (5, 2, 3)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [28]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

#[your code here]

c = np.transpose(b,(1,2,0))

print(c)

c.shape

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

In [31]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

#[your code here]

d= a+c

print("Shape of a", a.shape)
print("Shape of a", d.shape)

#Now each one of the dimensions has the same value

Shape of a (2, 3, 5)
Shape of a (2, 3, 5)


In [34]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

#[your code here]

print("a",a)

print("d",d)

#Each one of the values in array d is equal to the values in array a +1

a [[[0.30429719 0.96764391 0.52616975 0.43786554 0.72113294]
  [0.71453878 0.66059798 0.09831853 0.05460183 0.5770227 ]
  [0.42638266 0.85724564 0.56413599 0.02797983 0.59646838]]

 [[0.5264602  0.21354076 0.13775215 0.18327499 0.8890365 ]
  [0.8344566  0.07674443 0.05630981 0.0211732  0.00271911]
  [0.40654824 0.385428   0.20343194 0.86626533 0.10521698]]]
d [[[1.30429719 1.96764391 1.52616975 1.43786554 1.72113294]
  [1.71453878 1.66059798 1.09831853 1.05460183 1.5770227 ]
  [1.42638266 1.85724564 1.56413599 1.02797983 1.59646838]]

 [[1.5264602  1.21354076 1.13775215 1.18327499 1.8890365 ]
  [1.8344566  1.07674443 1.05630981 1.0211732  1.00271911]
  [1.40654824 1.385428   1.20343194 1.86626533 1.10521698]]]


In [35]:
#12. Multiply a and c. Assign the result to e.

#[your code here]

e = a*c



In [40]:
#13. Does e equal to a? Why or why not?

#[your code here]
print("a:", a  )
print("e:", e  )

print("Comparison:", a ==e)


#Array c is the transpose of matrix b which is a matrix of ones. So any number multiplied by one is itself

a: [[[0.30429719 0.96764391 0.52616975 0.43786554 0.72113294]
  [0.71453878 0.66059798 0.09831853 0.05460183 0.5770227 ]
  [0.42638266 0.85724564 0.56413599 0.02797983 0.59646838]]

 [[0.5264602  0.21354076 0.13775215 0.18327499 0.8890365 ]
  [0.8344566  0.07674443 0.05630981 0.0211732  0.00271911]
  [0.40654824 0.385428   0.20343194 0.86626533 0.10521698]]]
e: [[[0.30429719 0.96764391 0.52616975 0.43786554 0.72113294]
  [0.71453878 0.66059798 0.09831853 0.05460183 0.5770227 ]
  [0.42638266 0.85724564 0.56413599 0.02797983 0.59646838]]

 [[0.5264602  0.21354076 0.13775215 0.18327499 0.8890365 ]
  [0.8344566  0.07674443 0.05630981 0.0211732  0.00271911]
  [0.40654824 0.385428   0.20343194 0.86626533 0.10521698]]]
Comparison: [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [42]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

#[your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


print("d_max is:", d_max)
print("d_min is:", d_min)
print("d_mean is:", d_mean)





d_max is: 1.9676439144619775
d_min is: 1.0027191092293628
d_mean is: 1.4147586620062276


In [43]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

#[your code here]


f = np.empty(d.shape)



In [ ]:
#16. Populate the values in f. 
For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.

In [46]:
#[your code here]

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75


# Print the arrays 'd' and 'f'
print("Array 'd':\n", d)
print("\nArray 'f':\n", f)




Array 'd':
 [[[1.30429719 1.96764391 1.52616975 1.43786554 1.72113294]
  [1.71453878 1.66059798 1.09831853 1.05460183 1.5770227 ]
  [1.42638266 1.85724564 1.56413599 1.02797983 1.59646838]]

 [[1.5264602  1.21354076 1.13775215 1.18327499 1.8890365 ]
  [1.8344566  1.07674443 1.05630981 1.0211732  1.00271911]
  [1.40654824 1.385428   1.20343194 1.86626533 1.10521698]]]

Array 'f':
 [[[ 25. 100.  75.  75.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 75.  75.  75.  25.  75.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.   0.]
  [ 25.  25.  25.  75.  25.]]]


In [75]:
#17. Print d and f. Do you have your expected f?


#For instance, if your d is:
d=np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
    [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
    [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

   [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
    [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
    [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])



for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
"""
Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[your code here]


print(f)



[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


In [84]:
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
"""("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


print("d is:",d)

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
#[your code here]

f = np.empty(d.shape, dtype=str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = "A"
            elif d[i, j, k] == d_max:
                f[i, j, k] = "E"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"

print("f is: ",f)

d is: [[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
f is:  [[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
